### ISSUE TITLE
All docker-machine commands worked

### ISSUE THREAD

**Issue by zchee** [nathanleclaire/docker-machine-xhyve#1]
@nathanleclaire 
Sorry, does not issue.

By rewriting the code, All docker-machine `commands` worked now.
`ssh`, `eval`, `ls` etc...

And, `dhcpd_release` not found the issue is clear.
It will parse exactly machine IP.

but, folder shared and daemonize issue there are still.
I want an advice, would I be good to send a PR in this repository?

**Comment by nathanleclaire** [comment]
Sure, if you need some help feel free to make a PR and I'll do my best.

**Comment by zchee** [comment]
Thanks! and I was surprised fast reply :)

Because there is still a little bit of problem where it is different from such as `daemonize` and `shared folder`, I'll fix, and PR.

One moment, please...

**Comment by zchee** [comment]
@nathanleclaire 
Because I created the PR thread, this will close.
https://github.com/nathanleclaire/docker-machine-xhyve/pull/2
