### ISSUE TITLE
docker-machine's new plugin model can not parse args correctly

### ISSUE THREAD

**Issue by xiaohui** [nathanleclaire/docker-machine-xhyve#3]
When I run `./docker-machine_darwin-amd64  ls --driver xhyve` it output the "Incorrect Usage" information and then some help usage.

> Incorrect Usage.
> 
> Usage: docker-machine ls [OPTIONS] [arg...]
> 
> List machines
> 
> Options:
> 
>    --quiet, -q                  Enable quiet mode
>    --filter [--filter option --filter option]   Filter output based on conditions provided

_Basic environment_:
- docker-machine:  
  `nathanleclaire/machine:libmachine_rpc_plugins` with https://github.com/nathanleclaire/machine/commit/0b4755f39d96d3b42be8c577d13ac68e34ecdada compiled with `make` command
- docker-machine-xhyve: master branch with dfb0d8bbbc43beca22f8136c43b68c0610889a13 compiled with go1.5
- Mac OS X Yosemite 10.10.5
- Go: 1.5

**Comment by zchee** [comment]
@xiaohui 
+1
but, If so nathanleclaire is busy I'm going to cure with my [docker-machine-xhyve](https://github.com/zchee/docker-machine-xhyve) repo.

**Comment by zchee** [comment]
@xiaohui 
Sorry, I did not read well.

Could you try `./docker-machine_darwin-amd64 ls` ?
I think the flag is not required.

**Comment by xiaohui** [comment]
@zchee , if the flag is not given, it will use the default driver(virtualbox), in my enviroment, it will output like:

> Error attempting to invoke binary for plugin: Error attempting to serve plugin: Error trying to locate plugin binary: exec: "docker-machine-virtualbox": executable file not found in $PATH

**Comment by zchee** [comment]
@xiaohui Check `$HOME/.docker/machine/machines/` dir.
If exists dir create by other than xhyve drivers, required `docker-machine-****` binary.
e.g. `docker-machine-virtualbox`, `docker-machine-vmwarefusion`
This is because the implementation of libmachine has been changed.

However, you do not need to create a binary corresponding to the other driver for now.
`nathanleclaire/machine/libmachine_rpc_plugins` branch is develop.

So, if you try xhyve driver, Ideally empty the `$HOME/.docker/machine/machines/` dir.
e.g.

```
mv $HOME/.docker/machine/machines/ $HOME/.docker/machine/_machines/
```

This problem would be solved if it is merged `nathanleclaire/machine/libmachine_rpc_plugins` branch into the `docker/machine` of the master branch.

**Comment by zchee** [comment]
@xiaohui If you were only to xhyve driver vm dir, `./docker-machine_darwin-amd64 ls` will succeed.

**Comment by xiaohui** [comment]
@zchee it works by following your instruction, but I still don't know  why `./docker-machine_darwin-amd64 ls --driver xhyve` is not correct. It is not just the driver of xhyve, but also the driver of others use the new plugin model.

**Comment by xiaohui** [comment]
@zchee  sorry, I mis-understand  the usage.

**Comment by nathanleclaire** [comment]
> ./docker-machine_darwin-amd64 ls --driver xhyve

`ls` does not accept such a flag -- perhaps you are thinking of `docker-machine ls --filter driver=xhyve`?

**Comment by xiaohui** [comment]
@zchee @nathanleclaire I have fixed the problem, thank you all. BTW, it will be cool if --filter flag is supported.

**Comment by nathanleclaire** [comment]
@xiaohui I'm not sure what you mean, but `ls --filter` should work just fine.  With the new plugins no functionality should be lost (outside of not having drivers work if you don't have the plugin binary available).
